frr version 9.0
hostname r0
log syslog informational
!
interface eth1
 ip address 10.0.0.1/30
!
interface eth2
 ip address 10.0.1.1/30
 ip ospf cost 10
!
interface eth3
 ip address 10.0.2.1/30
 ip ospf cost 40
!
router ospf
 ospf router-id 0.0.0.0
 network 10.0.0.0/30 area 0
 network 10.0.1.0/30 area 0
 network 10.0.2.0/30 area 0
!
