frr version 9.0
hostname r2
log syslog informational
!
interface eth1
 ip address 10.0.2.2/30
!
interface eth2
 ip address 10.0.4.1/30
!
ip route 10.0.5.0/30 10.0.4.2
!
router rip
 network 10.0.2.0/30
 network 10.0.4.0/30
 redistribute static
 timers basic 10 30 30
!